version: '3'

services:
  frontend:
    image: frontend
    container_name: server-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 80:80
    environment:
      - BACKEND=http://localhost:8080
    depends_on:
      - backend
    networks:
      - server-net

  backend:
    image: backend
    container_name: server-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '8080:3000'
    environment:
      - PORT=3000
      - MYSQL_HOST=db
      - MYSQL_DATABASE=dbProducts
      - MYSQL_USER=userProducts
      - MYSQL_PASSWORD=12345
    depends_on:
      - db
    networks:
      - server-net

  db:
    image: mysql:8.0.25
    container_name: server-db
    environment:
      - MYSQL_DATABASE=dbProducts
      - MYSQL_USER=userProducts
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql-data:/docker-entrypoint-initdb.d
    networks:
      - server-net

networks:
  server-net:
